### ISSUE TITLE
",vs" needs renamed properly to .vs

### ISSUE THREAD

**Issue by gbowne1** [taotnpwaft/discordbot#13]
I inadvertently named the .vs folder ,vs for Visual Studio.

Rename to the correct .vs

Also test the configurations for Visual Studio.

**Comment by hitblast** [comment]
Working on it ;)

Test configurations for Visual Studio might take a while since I don't have VS installed.

**Comment by gbowne1** [comment]
Got the PR and your question.
Merged.

The included .pyproj needs to be tested in Visual Studio 2019/2022.
