### ISSUE TITLE
Update backend to support cogs and extensibility.

### ISSUE THREAD

**Issue by hitblast** [taotnpwaft/discordbot#20]
This enhancement involves implementing `discord.ext.commands.Cog` class and separating the functionality of the bot into different Python scripts. The goal here is to have all of the commands and features be located in a new `cogs` folder so that:

- [x] It provides the developers with an extensible codebase to add more features without breaking / affecting other ones.
- [x] It provides a neat and clean structure for the codebase.

**Comment by hitblast** [comment]
Update: Cogs have been implemented at an infant stage with [this commit](https://github.com/taotnpwaft/discordbot/commit/8092238d5d3c739e077d9598836434559e709412) of mine.

**Comment by gbowne1** [comment]
I think adding Cogs is a great idea, after doing some reading on the subject.

**Comment by hitblast** [comment]
> I think adding Cogs is a great idea, after doing some reading on the subject.

@gbowne1 Oh one bonus thing I did as well is I replaced `discord.Client` with `discord.ext.commands.Bot` for future-proofing. Both of them work nearly the same so I don't think anyone will have any problems dealing with it.

**Comment by gbowne1** [comment]
@hitblast Yeah.  Future proofing is good :-)

From every example I have seen, looks like it made their project work pretty well, code wise.
