### ISSUE TITLE
Fix tasks.json and launch.json

### ISSUE THREAD

**Issue by gbowne1** [taotnpwaft/discordbot#3]
The current files:

 - tasks.json
 - launch.json 

Don't appear to work as Microsoft describes in their Pyton Debug, etc. documentation.

These need to be fixed.

**Comment by gbowne1** [comment]
Sfill some minor issues with the Run, Build, Debug configs and settings files in this project.  .

I added common Python extensions to extensions.json from the marketplace.

**Comment by gbowne1** [comment]
.vs/discordbot.pyproj project file needs to be tested with Visual Studio 2019/2022.  There is also a .sln file.  Does it need a .suo as well?
 
I need to reinstall Visual Studio in my Windows VM.

@idormain ?

**Comment by idormain** [comment]
You do not need the suo file to be saved to source control. It’s a user options file.

**Comment by gbowne1** [comment]
I didn't think so.. just wasn't sure.

**Comment by gbowne1** [comment]
@idormain 

Did/can you have a look at the .sln and .pyproj to see if it looks ok or works?  Thanks so much mate.
